# Generated by Django 3.2.5 on 2026-02-22 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagemcliente',
            name='onibus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viajens.onibus'),
        ),
    ]
